document.addEventListener('DOMContentLoaded', async()=>{
  const b=await KoguShell.initShell({currentPage:'/modules/core/perfiles/perfiles.html',title:'Perfiles',description:'CRUD de perfiles y asignación de permisos.',requiredPermission:'screen.catalogos.perfiles'});
  if(!b) return;
  const c=document.getElementById('pageContent');
  c.innerHTML=`<div class="split"><div class="card"><div class="row"><div><div class="eyebrow">Perfiles</div><h2>Listado</h2></div><button class="btn primary" id="refreshBtn">Actualizar</button></div><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>Nombre</th><th>Descripción</th><th>Permisos</th><th>Activo</th><th>Acciones</th></tr></thead><tbody id="rows"></tbody></table></div></div><div class="stack"><div class="card"><div class="row"><div><div class="eyebrow">Formulario</div><h2 id="formTitle">Alta de perfil</h2></div><span class="chip" id="modeChip">Alta</span></div><div class="stack" style="margin-top:16px"><input type="hidden" id="perfil_id"/><div><div class="label-text">Nombre</div><input class="input" id="nombre"/></div><div><div class="label-text">Descripción</div><input class="input" id="descripcion"/></div><div class="page-actions"><button class="btn primary" id="saveBtn">Guardar</button><button class="btn" id="newBtn">Nuevo</button></div></div></div><div class="card"><div class="eyebrow">Permisos</div><h2>Asignación del perfil</h2><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th></th><th>Clave</th><th>Descripción</th><th>Activo</th></tr></thead><tbody id="permRows"></tbody></table></div><div class="page-actions" style="margin-top:16px"><button class="btn primary" id="savePermsBtn">Guardar permisos</button></div></div></div>`;
  let perfiles=[], permisos=[];
  function val(id){ return document.getElementById(id).value.trim(); }
  function reset(){ document.getElementById('perfil_id').value=''; document.getElementById('nombre').value=''; document.getElementById('descripcion').value=''; document.getElementById('formTitle').textContent='Alta de perfil'; document.getElementById('modeChip').textContent='Alta'; renderPerms([]); }
  async function loadPermisos(){ const res=await KoguApi.apiFetch('/protected/core/permisos'); permisos=KoguApi.unwrapRows(res); renderPerms([]); }
  function renderPerms(selected){ document.getElementById('permRows').innerHTML=(permisos||[]).map(p=>`<tr><td><input type="checkbox" class="perm-check" value="${p.permiso_id||p.id||p.clave}" ${selected.includes(String(p.permiso_id||p.id||p.clave))?'checked':''}></td><td>${KoguUi.escapeHtml(p.clave||'')}</td><td>${KoguUi.escapeHtml(p.descripcion||'')}</td><td>${KoguUi.statusBadge(p.activo?'activo':'inactivo')}</td></tr>`).join(''); }
  async function load(){ const res=await KoguApi.apiFetch('/protected/core/perfiles'); perfiles=KoguApi.unwrapRows(res); document.getElementById('rows').innerHTML=perfiles.map(r=>`<tr><td>${KoguUi.escapeHtml(r.nombre||'')}</td><td>${KoguUi.escapeHtml(r.descripcion||'')}</td><td>${KoguUi.int(r.total_permisos||0)}</td><td>${KoguUi.statusBadge(r.activo?'activo':'inactivo')}</td><td><button class="btn btn-edit" data-id="${r.perfil_id||r.id}">Editar</button></td></tr>`).join(''); document.querySelectorAll('.btn-edit').forEach(x=>x.onclick=async()=>{ const res=await KoguApi.apiFetch('/protected/core/perfiles/'+x.dataset.id); const d=KoguApi.unwrapData(res); document.getElementById('perfil_id').value=d.perfil?.perfil_id||d.perfil?.id||x.dataset.id; document.getElementById('nombre').value=d.perfil?.nombre||''; document.getElementById('descripcion').value=d.perfil?.descripcion||''; document.getElementById('formTitle').textContent='Editar perfil'; document.getElementById('modeChip').textContent='Edición'; renderPerms((d.permisos||[]).map(p=>String(p.permiso_id||p.id||p.clave))); }); }
  document.getElementById('refreshBtn').onclick=load; document.getElementById('newBtn').onclick=reset;
  document.getElementById('saveBtn').onclick=async()=>{ try{ const payload={nombre:val('nombre'), descripcion:val('descripcion')}; if(!payload.nombre) throw new Error('Nombre es obligatorio.'); const id=document.getElementById('perfil_id').value; if(id){ await KoguApi.apiFetch('/protected/core/perfiles/'+id,{method:'PUT',body:JSON.stringify(payload)}); KoguApi.toast('Perfil actualizado','success'); } else { await KoguApi.apiFetch('/protected/core/perfiles',{method:'POST',body:JSON.stringify(payload)}); KoguApi.toast('Perfil creado','success'); } reset(); await load(); }catch(err){ KoguApi.toast(err.message,'error'); } };
  document.getElementById('savePermsBtn').onclick=async()=>{ try{ const id=document.getElementById('perfil_id').value; if(!id) throw new Error('Selecciona un perfil.'); const permisosSeleccionados=[...document.querySelectorAll('.perm-check:checked')].map(x=>x.value); await KoguApi.apiFetch('/protected/core/perfiles/'+id+'/permisos',{method:'PUT',body:JSON.stringify({permisos:permisosSeleccionados})}); KoguApi.toast('Permisos actualizados','success'); await load(); }catch(err){ KoguApi.toast(err.message,'error'); } };
  await Promise.all([loadPermisos(), load()]);
});